version: 2
updates:
- package-ecosystem: gomod
  directory: "/backend"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cloud.google.com/go
    versions:
    - 0.77.0
    - 0.78.0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: html-to-image
    versions:
    - 1.6.0
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: next
    versions:
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: y18n
    versions:
    - 4.0.1
- package-ecosystem: npm
  directory: "/ogp_functions"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: "@google-cloud/storage"
    versions:
    - 5.8.0
