version: "3"
services:
  datastore:
    build:
      context: ./docker/datastore
      dockerfile: Dockerfile
    tty: true
    environment:
      DATASTORE_PROJECT_ID: midare-local
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:5000
    ports:
      - "127.0.0.1:5000:5000"