name: Deploy OGP Function

on:
  push:
    branches:
      - master
    paths-ignore:
    - 'frontend/**'
    - 'backend/**'

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          access_token_lifetime: '900s'

      - name: Set up Cloud SDK 
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploy to Cloud Functions
        run: |
            cd ogp_functions
            yarn install
            yarn deploy
